
version: 2

models:
    - name: orders
      description: "A starter dbt model"
      columns:
          - name: order_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: order_items
      description: "A starter dbt model"
      columns:
          - name: order_item_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
      
    - name: order_details
      description: "A order_details dbt model"
      
    - name: daily_product_revenue
      description: "A order_details dbt model"
      